site_name: CampaignManagerService
site_description: Service that help in creating and managing all media campaigns

nav:
  - Home: index.md
  - API Endpoints: endpoints.md
  - Tech Stack: techstack.md
